# Generated by Django 4.2.1 on 2024-04-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='desc',
        ),
    ]
