# Generated by Django 4.2.1 on 2024-04-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_login_email_remove_login_phone_login_pss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
