# Generated by Django 4.2.1 on 2024-04-27 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_login_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('place_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_type', models.CharField(choices=[('hospital', 'Animal Hospital/Clinic'), ('sitter', 'Pet Sitter'), ('ngo', 'Pet-related NGO')], max_length=50)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.place')),
            ],
        ),
    ]
